version: 2

project_name: cigno

before:
  hooks:
    - go mod tidy

builds:
  - id: cigno
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X cigno/cmd.version={{.Version}}

archives:
  - formats: [tar.gz]
    # archive name: cigno_linux_amd64.tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Os }}_{{ .Arch }}

checksum:
  name_template: "checksums.txt"

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^build:"
